#sched_cfs.o : common.o  test_sched_cfs.o 
#sched_cfs-objs += common.o  test_sched_cfs.o

#obj-m += sched_cfs.o
obj-m += test_spin_lock.o test_irq_disable.o test_irq_save.o test_kmalloc.o test_smp_processor_id.o test_preempt.o test___this_cpu_preempt_check.o
